// Secure Quote Request API - Phase 1
// Sends quote request to Stephen's team WITHOUT client email

import { createClient } from '@supabase/supabase-js';

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY
);

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { cruiseId, clientName, userId } = req.body;

    // Validate required fields
    if (!cruiseId || !clientName || !userId) {
      return res.status(400).json({ 
        error: 'Missing required fields: cruiseId, clientName, userId' 
      });
    }

    // Verify user is authenticated
    const { data: user, error: userError } = await supabase.auth.getUser(req.headers.authorization?.replace('Bearer ', ''));
    
    if (userError || !user) {
      return res.status(401).json({ error: 'Unauthorized' });
    }

    // Get cruise details from Supabase
    const { data: cruise, error: cruiseError } = await supabase
      .from('cruises')
      .select('*')
      .eq('id', cruiseId)
      .single();

    if (cruiseError || !cruise) {
      return res.status(404).json({ error: 'Cruise not found' });
    }

    // Check if pricing is available
    if (cruise.pricingStatus !== 'Available') {
      return res.status(400).json({ error: 'Pricing not available for this cruise' });
    }

    // Generate secure token for quote form
    const quoteToken = generateSecureToken();
    const quoteId = `quote_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;

    // Store quote request in database
    const { error: insertError } = await supabase
      .from('quote_requests')
      .insert({
        id: quoteId,
        cruise_id: cruiseId,
        user_id: userId,
        client_name: clientName,
        token: quoteToken,
        status: 'pending',
        created_at: new Date().toISOString(),
        expires_at: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString() // 7 days
      });

    if (insertError) {
      console.error('Database insert error:', insertError);
      return res.status(500).json({ error: 'Failed to create quote request' });
    }

    // Prepare email to Stephen's team (NO CLIENT EMAIL)
    const quoteFormUrl = `${process.env.NEXT_PUBLIC_APP_URL}/quote?id=${quoteId}&token=${quoteToken}`;
    
    const emailData = {
      to: 'reservations@interlinetravel.com.au',
      subject: `New Quote Request - ${cruise.ship_name} (${cruise.cruise_line})`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: #0f172a;">New Quote Request</h2>
          
          <div style="background: #f8fafc; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <h3 style="color: #1e293b; margin-top: 0;">Client Information</h3>
            <p><strong>Client Name:</strong> ${clientName}</p>
            <p style="color: #64748b; font-size: 14px;">
              <em>Note: Client email is protected for privacy. Use the secure quote form below.</em>
            </p>
          </div>

          <div style="background: #f0f9ff; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <h3 style="color: #1e293b; margin-top: 0;">Cruise Details</h3>
            <p><strong>Cruise Line:</strong> ${cruise.cruise_line}</p>
            <p><strong>Ship:</strong> ${cruise.ship_name}</p>
            <p><strong>Departure Date:</strong> ${cruise.departure_date}</p>
            <p><strong>Duration:</strong> ${cruise.nights} nights</p>
            <p><strong>Region:</strong> ${cruise.region}</p>
            <p><strong>Departure Port:</strong> ${cruise.departure_port}</p>
            <p><strong>Arrival Port:</strong> ${cruise.arrival_port}</p>
            ${cruise.itinerary ? `<p><strong>Itinerary:</strong> ${cruise.itinerary}</p>` : ''}
          </div>

          <div style="background: #059669; padding: 20px; border-radius: 8px; text-align: center; margin: 30px 0;">
            <h3 style="color: white; margin-top: 0;">Secure Quote Form</h3>
            <p style="color: white; margin-bottom: 20px;">
              Click below to access the secure quote form. This link expires in 7 days.
            </p>
            <a href="${quoteFormUrl}" 
               style="background: white; color: #059669; padding: 12px 24px; text-decoration: none; 
                      border-radius: 6px; font-weight: bold; display: inline-block;">
              Complete Quote Form
            </a>
          </div>

          <div style="border-top: 1px solid #e2e8f0; padding-top: 20px; margin-top: 30px;">
            <p style="color: #64748b; font-size: 12px;">
              This quote request was generated by Interline Asia's secure booking system.
              The quote form link is unique and expires automatically for security.
            </p>
          </div>
        </div>
      `
    };

    // Send email using Brevo API
    const emailResponse = await fetch('https://api.brevo.com/v3/smtp/email', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'api-key': process.env.BREVO_API_KEY
      },
      body: JSON.stringify({
        sender: {
          name: 'Interline Asia',
          email: 'noreply@interlineasia.com'
        },
        to: [{ email: 'reservations@interlinetravel.com.au' }],
        subject: emailData.subject,
        htmlContent: emailData.html
      })
    });

    if (!emailResponse.ok) {
      console.error('Email send failed:', await emailResponse.text());
      return res.status(500).json({ error: 'Failed to send quote request email' });
    }

    res.status(200).json({
      success: true,
      message: 'Quote request sent successfully',
      quoteId: quoteId
    });

  } catch (error) {
    console.error('Quote request error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
}

// Generate secure token
function generateSecureToken() {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  let token = '';
  for (let i = 0; i < 32; i++) {
    token += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return token;
}