// Fixed Quote Request API - Sends quote request emails
// Handles quote requests and forwards them to reservations team

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    console.log('QUOTE API: Request received:', JSON.stringify(req.body, null, 2));
    
    const { cruiseId, clientName, userId, userEmail, dealId } = req.body;

    // Validate required fields
    if (!cruiseId || !clientName || !userId) {
      console.error('QUOTE ERROR: Missing required fields:', { cruiseId, clientName, userId });
      return res.status(400).json({ 
        error: 'Missing required fields: cruiseId, clientName, userId' 
      });
    }

    // Skip user authentication check - we'll use service role for database operations
    console.log('QUOTE API: Processing quote request for user:', userId);

    // Create a simple email-only quote request (no database storage needed)
    console.log('QUOTE API: Preparing email notification');

    // Prepare email content with client information
    const emailSubject = `New Quote Request - Cruise ID: ${cruiseId}`;
    const emailHtml = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2 style="color: #0f172a;">New Quote Request</h2>
        
        <div style="background: #f8fafc; padding: 20px; border-radius: 8px; margin: 20px 0;">
          <h3 style="color: #1e293b; margin-top: 0;">Client Information</h3>
          <p><strong>Client Name:</strong> ${clientName}</p>
          <p><strong>Client Email:</strong> ${userEmail || 'Not provided'}</p>
          <p><strong>User ID:</strong> ${userId}</p>
          <p><strong>Request Time:</strong> ${new Date().toLocaleString()}</p>
        </div>

        <div style="background: #f0f9ff; padding: 20px; border-radius: 8px; margin: 20px 0;">
          <h3 style="color: #1e293b; margin-top: 0;">Cruise Details</h3>
          <p><strong>Cruise ID:</strong> ${cruiseId}</p>
          <p><strong>Deal ID:</strong> ${dealId || cruiseId}</p>
          <p><em>Please check your cruise database for full details using the Cruise ID above.</em></p>
        </div>

        <div style="background: #059669; padding: 20px; border-radius: 8px; color: white; margin: 30px 0;">
          <h3 style="margin-top: 0;">Next Steps</h3>
          <p>Please prepare a quote for this client and send it directly to their email address listed above.</p>
          <p>Expected response time: 24-48 hours</p>
        </div>

        <div style="border-top: 1px solid #e2e8f0; padding-top: 20px; margin-top: 30px;">
          <p style="color: #64748b; font-size: 12px;">
            This quote request was generated by Interline Asia's booking system.
          </p>
        </div>
      </div>
    `;

    console.log('QUOTE API: Sending email notification');

    // Send email using Brevo API to both addresses
    const emailResponse = await fetch('https://api.brevo.com/v3/smtp/email', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'api-key': process.env.BREVO_API_KEY
      },
      body: JSON.stringify({
        sender: {
          name: 'Interline Asia',
          email: 'noreply@interlineasia.com'
        },
        to: [
          { email: 'reservations@interlinetravel.com.au' }
        ],
        cc: [
          { email: 'admin@interlineasia.com' }
        ],
        subject: emailSubject,
        htmlContent: emailHtml
      })
    });

    if (!emailResponse.ok) {
      const errorText = await emailResponse.text();
      console.error('QUOTE ERROR: Email send failed:', errorText);
      return res.status(500).json({ 
        error: 'Failed to send quote request email',
        details: errorText 
      });
    }

    console.log('QUOTE API: Email sent successfully');

    res.status(200).json({
      status: 'success',
      success: true,
      message: 'Quote request sent successfully'
    });

  } catch (err) {
    console.error('QUOTE ERROR:', err);
    return res.status(500).json({ 
      error: err.message || 'Unknown server error',
      details: err.stack 
    });
  }
}